//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("   9313875e-59ca-446b-9dad-fb84db6a9d03")]
        public string clientId {
            get {
                return ((string)(this["clientId"]));
            }
            set {
                this["clientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@" Gj5nS9wyYHRadaVffz5VKB4v4wlVWyPhcJvrTD4NHtNC6UPzvQct7ipnaMX1vztop+sXgaqfI+uKPyP5dJo2V8bjOTF+9ckviSzmAAyX0G7Pw6l11mn+ar8c/NTXRk5tBNgA0XPlsDFmaLS1IHgRyOP4T605hi+vFULXpW6ErwhYN70FbnxiKlvmhGN0iDZZdnS7e4MV4xEN3Z+ZWIwOsZ8gVKOQomYA2ZgYThZXWZwgb+Ag9dztrMcXYfsHbZZm2tBfMbRxTdO7M/s5Vq3S9w==")]
        public string secretKey {
            get {
                return ((string)(this["secretKey"]));
            }
            set {
                this["secretKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"Data Source=.\\SQLEXPRESS;\r\nInitial Catalog=AccountingCoreDB;\r\nIntegrated Securi" +
            "ty=True\";")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastChequeReminderDate {
            get {
                return ((global::System.DateTime)(this["LastChequeReminderDate"]));
            }
            set {
                this["LastChequeReminderDate"] = value;
            }
        }
    }
}
